-- MySQL Script generated by MySQL Workbench
-- Tue Mar 27 11:36:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cadastro_placas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cadastro_placas` ;

-- -----------------------------------------------------
-- Schema cadastro_placas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastro_placas` DEFAULT CHARACTER SET utf8 ;
USE `cadastro_placas` ;

-- -----------------------------------------------------
-- Table `cadastro_placas`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro_placas`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `cadastro_placas`.`pessoa` (
  `nome` VARCHAR(30) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(15) NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `rg`, `placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro_placas`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro_placas`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `cadastro_placas`.`veiculo` (
  `tipo_de_veiculo` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `ano` INT NOT NULL,
  `proprietario` VARCHAR(30) NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  `pessoa_cpf` VARCHAR(11) NOT NULL,
  `pessoa_rg` VARCHAR(15) NOT NULL,
  `pessoa_placa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`proprietario`, `placa`),
  INDEX `fk_veiculo_pessoa_idx` (`pessoa_cpf` ASC, `pessoa_rg` ASC, `pessoa_placa` ASC),
  CONSTRAINT `fk_veiculo_pessoa`
    FOREIGN KEY (`pessoa_cpf` , `pessoa_rg` , `pessoa_placa`)
    REFERENCES `cadastro_placas`.`pessoa` (`cpf` , `rg` , `placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
